### ISSUE TITLE
Nativescript 7

### ISSUE THREAD

**Issue by kfw9257** [vakrilov/ngrx-devtools-nativescript#10]
Are there any plans to update this plugin to support NativeScript 7? Not seeing the dock monitor when running an Angular 10/NS 7 app.

**Comment by vakrilov** [comment]
Currently, I don't have the resources to actively work on this repo, but will be happy to review and merge PRs

**Comment by rob4226** [comment]
@vakrilov @kfw9257 Hey guys, I just submitted a pull request #11  to update the project to NativeScript 7 and latest versions of Angular. Works great!

**Comment by vakrilov** [comment]
This is awesome! Thanks @Rob4226
