### ISSUE TITLE
Npm peer dependency error

### ISSUE THREAD

**Issue by Joe3Huang** [vakrilov/ngrx-devtools-nativescript#7]
Hi vakrilov, when I installed the package, the peer dependency error occurred.

The package requires angular 4.2.6 but I am using angular 5. 

How can I solve this? Can I use this package with angular 5?

**Comment by jogboms** [comment]
@Joe3Huang Technically, it should still work with `v5`

**Comment by vakrilov** [comment]
Packages have been updated to angular 8
